name: fampay
description: A demo app showcasing contextual cards container
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7
  crypto: ^3.0.2
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fampay.png
#    - assets/lock_hand.png
#    - assets/mascot.png
#    - assets/avatar.png
